version: '3'

services:
  # Machine 1 - Apache 2.2.3 (Vulnerable)
  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    environment:
      - FLAG=FLAG{apache_2_2_3_vulnerable}
    networks:
      ctf_network:
        ipv4_address: 172.20.0.10

  # Machine 2 - Ubuntu with multiple SSH ports
  ubuntu_ssh:
    build:
      context: ./ubuntu_ssh
      dockerfile: Dockerfile
    environment:
      - FLAG=FLAG{multiple_ssh_ports}
    networks:
      ctf_network:
        ipv4_address: 172.20.0.63

  # Machine 3 - PHP and MySQL
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    environment:
      - FLAG=FLAG{sqli_vulnerable_php}
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ctf_db
    networks:
      ctf_network:
        ipv4_address: 172.20.0.169

  # Machine 4 - Ubuntu with vulnerable SSH
  ubuntu_vuln_ssh:
    build:
      context: ./ubuntu_vuln_ssh
      dockerfile: Dockerfile
    environment:
      - FLAG=FLAG{weak_ssh_config}
    networks:
      ctf_network:
        ipv4_address: 172.20.0.215

  # Machine 5 - Ghostcat vulnerable Tomcat
  ghostcat:
    build:
      context: ./ghostcat
      dockerfile: Dockerfile
    environment:
      - FLAG=FLAG{ghostcat_vulnerability}
    networks:
      ctf_network:
        ipv4_address: 172.20.0.189

  # Machine 6 - ExifTool vulnerable
  exiftool:
    build:
      context: ./exiftool
      dockerfile: Dockerfile
    environment:
      - FLAG=FLAG{exiftool_vulnerability}
    networks:
      ctf_network:
        ipv4_address: 172.20.0.213

  # Scoreboard
  scoreboard:
    build:
      context: ./scoreboard
      dockerfile: Dockerfile
    volumes:
      - scoreboard_data:/app/instance
    networks:
      ctf_network:
        ipv4_address: 172.20.0.100

  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - ovpn-data:/etc/openvpn
    restart: unless-stopped

networks:
  ctf_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  scoreboard_data:
  vpn_data:
  ovpn-data: 