services:
  # Machine 1 - Starting Point
  begin:
    build:
      context: ./begin
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      ctf_network:
        ipv4_address: 172.20.0.8
  # Machine 2 - SQL Injection
  sqli:
    build:
      context: ./sqli
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      ctf_network:
        ipv4_address: 172.20.0.10

  # Machine 3 - Ubuntu with multiple SSH ports
  ubuntu_ssh:
    build:
      context: ./ubuntu_ssh
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      ctf_network:
        ipv4_address: 172.20.0.63

  # Machine 4 - Shellshock vulnerability
  shellshock:
    build:
      context: ./shellshock
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      ctf_network:
        ipv4_address: 172.20.0.215

  # Machine 5 - Ghostcat vulnerable Tomcat
  ghostcat:
    build:
      context: ./ghostcat
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      ctf_network:
        ipv4_address: 172.20.0.189
      hidden_network:
        ipv4_address: 192.168.100.10

  # Machine 6 - Upload php vulnerable
  upload:
    build:
      context: ./upload
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      ctf_network:
        ipv4_address: 172.20.0.213

  # Machine 7 - Arlen Service Center (Hidden Network)
  arlenservice:
    build:
      context: ./arlenservice
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      hidden_network:
        ipv4_address: 192.168.100.20

  # OpenVPN Server
  openvpn:
    build:
      context: ./openvpn-server
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn-server/openvpn-data:/etc/openvpn
    restart: unless-stopped
    environment:
      - OVPN_NAT=1
    networks:
      ctf_network:
        ipv4_address: 172.20.0.250

  # Scoreboard Service
  scoreboard:
    build:
      context: ./scoreboard
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scoreboard/data:/app/data
      - ./scoreboard/flags.txt:/app/flags.txt
    networks:
      ctf_network:
        ipv4_address: 172.20.0.251

networks:
  ctf_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
  hidden_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24

volumes:
  scoreboard_data:
  vpn_data: